package args

type Args struct {
	Enable                         *bool
	Sort                           string
	Order                          string
	Offset                         string
	Limit                          string
	Search                         string
	AskRefresh                     string
	AskResponse                    string
	Write                          string
	ThingType                      string
	UUID                           *string
	WriteHistory                   string
	Field                          string
	Value                          string
	CompactPayload                 string
	CompactWithName                string
	Name                           *string
	AddToParent                    string
	GlobalUUID                     *string
	ClientId                       *string
	SiteId                         *string
	DeviceId                       *string
	SourceUUID                     *string
	ByPluginName                   bool
	TimestampGt                    *string
	TimestampLt                    *string
	Networks                       bool
	WithDevices                    bool
	WithPoints                     bool
	WithPriority                   bool
	WithTags                       bool
	PluginName                     string
	NetworkName                    *string
	DeviceName                     *string
	PointName                      *string
	AddressUUID                    *string
	AddressID                      *string
	ObjectType                     *string
	IoNumber                       *string
	IdGt                           *string
	IsRemote                       *bool
	IsMetadata                     bool
	NetworkUUID                    *string
	DeviceUUID                     *string
	WithMetaTags                   bool
	MetaTags                       *string
	MemberUUID                     *string
	ShowCloneNetworks              bool
	PointSourceUUID                *string
	HostUUID                       *string
	WithMembers                    bool
	WithMemberDevices              bool
	WithTeams                      bool
	WithViews                      bool
	WithGroups                     bool
	WithHosts                      bool
	WithComments                   bool
	WithWidgets                    bool
	WithViewTemplateWidgets        bool
	WithViewTemplateWidgetPointers bool
	WithTickets                    bool
	Target                         *string
	Notified                       *bool
}

var ArgsType = struct {
	Sort                           string
	Order                          string
	Offset                         string
	Limit                          string
	Search                         string
	AskRefresh                     string
	AskResponse                    string
	Write                          string
	ThingType                      string
	UUID                           string
	WriteHistory                   string
	Field                          string
	Name                           string
	Value                          string
	CompactPayload                 string // for a point would be presentValue
	CompactWithName                string // for a point would be presentValue and pointName
	AddToParent                    string
	GlobalUUID                     string
	ClientId                       string
	SiteId                         string
	DeviceId                       string
	SourceUUID                     string
	ByPluginName                   string
	TimestampGt                    string
	TimestampLt                    string
	WithNetworks                   string
	WithDevices                    string
	WithPoints                     string
	WithPriority                   string
	WithTags                       string
	PluginName                     string
	NetworkName                    string
	DeviceName                     string
	PointName                      string
	AddressUUID                    string
	AddressID                      string
	ObjectType                     string
	IoNumber                       string
	IdGt                           string
	IsRemote                       string
	IsMetadata                     string
	NetworkUUID                    string
	DeviceUUID                     string
	WithMetaTags                   string
	MetaTags                       string
	ShowCloneNetworks              string
	PointSourceUUID                string
	HostUUID                       string
	WithMembers                    string
	WithMemberDevices              string
	WithTeams                      string
	WithViews                      string
	WithGroups                     string
	WithHosts                      string
	WithComments                   string
	WithWidgets                    string
	WithViewTemplateWidgets        string
	WithViewTemplateWidgetPointers string
	WithTickets                    string
	Target                         string
	Notified                       string
}{
	Sort:                           "sort",
	Order:                          "order",
	Offset:                         "offset",
	Limit:                          "limit",
	Search:                         "search",
	AskRefresh:                     "ask_refresh",
	AskResponse:                    "ask_response",
	Write:                          "write",
	ThingType:                      "thing_type", // the type of thing like a point
	UUID:                           "uuid",
	WriteHistory:                   "write_history",
	Field:                          "field",
	Name:                           "name",
	Value:                          "value",
	CompactPayload:                 "compact_payload",
	CompactWithName:                "compact_with_name",
	AddToParent:                    "add_to_parent",
	GlobalUUID:                     "global_uuid",
	ClientId:                       "client_id",
	SiteId:                         "site_id",
	DeviceId:                       "device_id",
	SourceUUID:                     "source_uuid",
	ByPluginName:                   "by_plugin_name",
	TimestampGt:                    "timestamp_gt",
	TimestampLt:                    "timestamp_lt",
	WithNetworks:                   "with_networks",
	WithDevices:                    "with_devices",
	WithPoints:                     "with_points",
	WithPriority:                   "with_priority",
	WithTags:                       "with_tags",
	PluginName:                     "plugin_name",
	NetworkName:                    "network_name",
	DeviceName:                     "device_name",
	PointName:                      "point_name",
	AddressUUID:                    "address_uuid",
	AddressID:                      "address_id",
	ObjectType:                     "object_type",
	IoNumber:                       "io_number",
	IdGt:                           "id_gt",
	IsRemote:                       "is_remote",
	IsMetadata:                     "is_metadata",
	NetworkUUID:                    "network_uuid",
	DeviceUUID:                     "device_uuid",
	WithMetaTags:                   "with_meta_tags",
	MetaTags:                       "meta_tags",
	ShowCloneNetworks:              "show_clone_networks",
	PointSourceUUID:                "point_source_uuid",
	HostUUID:                       "host_uuid",
	WithMembers:                    "with_members",
	WithMemberDevices:              "with_member_devices",
	WithTeams:                      "with_teams",
	WithViews:                      "with_views",
	WithGroups:                     "with_groups",
	WithHosts:                      "with_hosts",
	WithComments:                   "with_comments",
	WithWidgets:                    "with_widgets",
	WithViewTemplateWidgets:        "with_view_template_widgets",
	WithViewTemplateWidgetPointers: "with_view_template_widget_pointers",
	WithTickets:                    "with_tickets",
	Target:                         "target",
	Notified:                       "notified",
}

var ArgsDefault = struct {
	Sort                           string
	Order                          string
	Offset                         string
	Limit                          string
	Search                         string
	AskRefresh                     string
	AskResponse                    string
	Write                          string
	ThingType                      string
	Field                          string
	Value                          string
	CompactPayload                 string
	CompactWithName                string
	AddToParent                    string
	PluginName                     string
	WithNetworks                   string
	WithDevices                    string
	WithPoints                     string
	WithPriority                   string
	WithTags                       string
	NetworkName                    string
	DeviceName                     string
	PointName                      string
	IsMetadata                     string
	NetworkUUID                    string
	DeviceUUID                     string
	WithMetaTags                   string
	MetaTags                       string
	ShowCloneNetworks              string
	WithMembers                    string
	WithMemberDevices              string
	WithTeams                      string
	WithViews                      string
	WithGroups                     string
	WithHosts                      string
	WithComments                   string
	WithWidgets                    string
	WithViewTemplateWidgets        string
	WithViewTemplateWidgetPointers string
	WithTickets                    string
}{
	Sort:                           "ID",
	Order:                          "DESC", // ASC or DESC
	Offset:                         "0",
	Limit:                          "25",
	Search:                         "",
	AskRefresh:                     "false",
	AskResponse:                    "false",
	Write:                          "false",
	ThingType:                      "point",
	Field:                          "name",
	Value:                          "",
	CompactPayload:                 "false",
	CompactWithName:                "false",
	AddToParent:                    "",
	PluginName:                     "false",
	WithNetworks:                   "false",
	WithDevices:                    "false",
	WithPoints:                     "false",
	WithPriority:                   "false",
	WithTags:                       "false",
	NetworkName:                    "",
	DeviceName:                     "",
	PointName:                      "",
	IsMetadata:                     "false",
	NetworkUUID:                    "",
	DeviceUUID:                     "",
	WithMetaTags:                   "false",
	MetaTags:                       "",
	ShowCloneNetworks:              "false",
	WithMembers:                    "false",
	WithMemberDevices:              "false",
	WithTeams:                      "false",
	WithViews:                      "false",
	WithGroups:                     "false",
	WithHosts:                      "false",
	WithComments:                   "false",
	WithWidgets:                    "false",
	WithViewTemplateWidgets:        "false",
	WithViewTemplateWidgetPointers: "false",
	WithTickets:                    "false",
}
