# Example configuration file for the server.
# Save it to `config.yml` when edited

server:
  keepaliveperiodseconds: 0 # 0 = use system default; set the interval in which keepalive packages will be sent. Only change this value if you know what you are doing.
  listenaddr: "0.0.0.0" # the address to bind on, leave empty to bind on all addresses
  rsport: 1616

  responseheaders: # response headers are added to every response (default: none)
  #    X-Custom-Header: "custom value"

database: # for database see (configure database section)
  dialect: sqlite3
  connection: data.db
  loglevel: "DEBUG" # options are: INFO, WARN, ERROR, SILENT (needs to be greater than or equal to global loglevel)

loglevel: "INFO" # options are: DEBUG, INFO, WARN, ERROR

pointhistory:
  enable: true
  cleaner:
    enable: true
    frequency: 600
    datapersistinghours: 24
  intervalhistorycreator:
    enable: true
    frequency: 10

mqtt:
  enable: true
  address: "localhost"
  port: 1883
  username: ""
  password: ""
  autoreconnect: true
  connectretry: true
  qos: 1
  retain: true
  globalbroadcast: false
  publishpointcov: true
  publishpointlist: false
  pointwritelistener: true
  publishschedulecov: true
  publishwchedulelist: false
  schedulewritelistener: true

notification:
  enable: false
  frequency: 60
  resendduration: 1
